name: "Semantic Version Release"
description: "This action is used to update the image tag."
inputs:
  github-user-name:
    description: "A user name for git operations in the release repository."
    required: true
  github-user-email:
    description: "A user email for git operations in the release repository."
    required: true
  github-user-token:
    description: "A user token for git operations in the release repository."
    required: true
  semantic-type:
    description: "Semantic type (major.minor.patch)."
runs:
  using: "node20"
  main: "index.js"
